//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_ROLES
    {
        public CV_ROLES()
        {
            this.CV_MANAGE_ROLES = new HashSet<CV_MANAGE_ROLES>();
        }
    
        public int ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string DELETE_ABILITY { get; set; }
        public string EDIT_ABILITY { get; set; }
        public string ADD_ABILITY { get; set; }
    
        public virtual ICollection<CV_MANAGE_ROLES> CV_MANAGE_ROLES { get; set; }
    }
}
