//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_XML_FRAGMENT
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> FRAGMENT_TYPE { get; set; }
        public string XML_DATA { get; set; }
    
        public virtual CV_FRAGMENT_TYPE CV_FRAGMENT_TYPE { get; set; }
        public virtual CV_USER CV_USER { get; set; }
    }
}
