//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.WCFService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSOContext : DbContext
    {
        public SSOContext()
            : base("name=nsi03")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CV_CLAIM> CV_CLAIM { get; set; }
        public virtual DbSet<CV_FRAGMENT_TYPE> CV_FRAGMENT_TYPE { get; set; }
        public virtual DbSet<CV_LOG> CV_LOG { get; set; }
        public virtual DbSet<CV_MANAGE_ROLES> CV_MANAGE_ROLES { get; set; }
        public virtual DbSet<CV_ROLES> CV_ROLES { get; set; }
        public virtual DbSet<CV_USER> CV_USER { get; set; }
        public virtual DbSet<CV_USER_INFO> CV_USER_INFO { get; set; }
        public virtual DbSet<CV_XML_FRAGMENT> CV_XML_FRAGMENT { get; set; }
    }
}
