//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.WCFService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSOEntities : DbContext
    {
        public SSOEntities()
            : base("name=SSOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CV_CLAIM> CV_CLAIM { get; set; }
        public DbSet<CV_MANAGE_ROLES> CV_MANAGE_ROLES { get; set; }
        public DbSet<CV_ROLES> CV_ROLES { get; set; }
        public DbSet<CV_USER> CV_USER { get; set; }
    }
}
